---
web1:
  username: "admin"
  password: "secret123"
  #It is recommended to use an authentication key with 32 or 64 bytes.
  session_cookie_authentication_key: "PjanW5cOBIlWzjLK23Q8NIo4va53e1bsgWmcqMdznVzkW3uEozfotj7MZsD7HpBo"
  #The encryption key, must be either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256 modes.
  session_store_encryption_key: "SQxqb3LKw1YFyAiy4j7FaGGJKeEzr8Db"
  services:
    apigw:
      addr: "http://172.16.50.2:8080"
    mockas:
      addr: "http://172.16.50.13:8080"